### ISSUE TITLE
Launch Tracker 🔴

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/lfe#109]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

To get your track ready for Exercism v3, the following needs to be done:

- [ ] [Configure online editor](https://github.com/exercism/lfe/issues/100)
- [ ] [Add key features](https://github.com/exercism/lfe/issues/101)
- [ ] [Add tags](https://github.com/exercism/lfe/issues/102)
- [ ] [Add prerequisites to Practice Exercises](https://github.com/exercism/lfe/issues/103)
- [ ] [Update status of track](https://github.com/exercism/lfe/issues/107)
- [ ] [Update status of Concept Exercises](https://github.com/exercism/lfe/issues/108)
- [ ] [Pass linting checks](https://github.com/exercism/lfe/issues/104)
- [ ] [Build Test Runner](https://github.com/exercism/lfe/issues/105)
- [ ] [Build Analyzer and Representer](https://github.com/exercism/lfe/issues/106) (optional)

This issue may be automatically added to over time. While track maintainers should check off completed items, please do not add/edit items in the list.

## Tracking

https://github.com/exercism/v3-launch/issues/7
